name: Prebuild TDLib for WASM
on:
  workflow_dispatch:
    inputs:
      tdlib:
        # https://github.com/tdlib/td/search?q=Update+version+to&type=commits
        description: "TDLib git ref (e.g. v1.8.0 or a commit hash)"
        type: string
        required: true

jobs:
  build-wasm:
    name: Build TDLib for Web
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: "tdlib/td"
          ref: ${{ inputs.tdlib }}
      - name: Install gperf
        run: sudo apt-get install -y -q gperf clang-14 libc++-dev libc++abi-dev tar wget
      - name: Install latest CMake
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v3.25.0/cmake-3.25.0-linux-x86_64.sh 
          chmod +x ./cmake-*.sh
          mkdir cmake
          ./cmake-*.sh --prefix=./cmake --skip-license
          sudo cp -RTv ./cmake /usr/
          cmake --version
      - name: Install emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          git pull
          ./emsdk install 3.1.1
          ./emsdk activate 3.1.1
          source ./emsdk_env.sh
          cd ..

      - name: Build for WASM
        run: |
          cd examples/web
          ./build-openssl.sh
          ./build-tdlib.sh

